const MOC_PRODUCTS_DATA = [
  {
    category: '1Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 1,
    checked: false,
  },
  {
    category: '2Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 2,
    checked: false,
  },
  {
    category: '3Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 3,
    checked: false,
  },
  {
    category: '4Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 4,
    checked: false,
  },
  {
    category: '5Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 5,
    checked: false,
  },
  {
    category: '6Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 6,
    checked: false,
  },
  {
    category: '7Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 7,
    checked: false,
  },
  {
    category: '8Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 8,
    checked: false,
  },
  {
    category: '9Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 9,
    checked: false,
  },
  {
    category: '10Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 10,
    checked: false,
  },
  {
    category: '11Эстетический уход 10',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 11,
    checked: false,
  },
  {
    category: '12Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 12,
    checked: false,
  },
  {
    category: '13Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 13,
    checked: false,
  },
  {
    category: '14Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 14,
    checked: false,
  },
  {
    category: '15Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 15,
    checked: false,
  },
  {
    category: '16Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 16,
    checked: false,
  },
  {
    category: '17Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 17,
    checked: false,
  },
  {
    category: '18Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 18,
    checked: false,
  },
  {
    category: '19Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 19,
    checked: false,
  },
  {
    category: '20Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 20,
    checked: false,
  },
  {
    category: '21Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 21,
    checked: false,
  },
  {
    category: '22Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 22,
    checked: false,
  },
  {
    category: '23Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 23,
    checked: false,
  },
  {
    category: '24Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 24,
    checked: false,
  },
  {
    category: '25Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 25,
    checked: false,
  },
  {
    category: '26Эстетический уход',
    subCategory: 'Скрабы',
    brand: 'Academie',
    goods: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
    id: 26,
    checked: false,
  },
];

export default MOC_PRODUCTS_DATA;
